import { useCallback, useEffect, useRef, useState } from "react";
import { BookOpen, ChevronRight, RefreshCw } from "./SemantixIcons";
import { app } from "../lib/bridge";
import { UsageRollingNumber } from "./UsageRollingNumber";
import { BorderBeam } from "./magicui/BorderBeam";
import { MagneticUsageMeter } from "./MagneticUsageMeter";
import { asArray } from "../lib/array";
import { useI18n } from "../lib/i18n";
import { formatTokens as formatCompactTokens } from "../lib/format";
import type { ContextInfo, ContextPanelInfo, SavingsTotals, WireUsage } from "../lib/types";

const formatTokens = (value: number | undefined) => formatCompactTokens(value).replace(/K$/, "k");

const copy = {
 en:{session:"This session",total:"All time",usage:"Token usage",input:"Input",output:"Output",requests:"requests",byModel:"By model",share:"Tokens · share",noModels:"No recorded model breakdown yet",unassigned:"Unassigned model",loading:"Loading…",error:"Could not refresh usage",retry:"Retry",cache:"Cache hit",turn:"Turn hit",avg:"Avg hit",cached:"cached",uncached:"uncached",notReported:"Not reported by model",memory:"Memory hits",recall:"Latest recall · matched memories",recalls:"Matches across recorded recalls",latestRecall:"Latest session recall",noRecall:"No recall yet",context:"Session context",used:"used",compact:"Compact at",canonical:"Before summary",projected:"After summary",reduction:"Latest context reduction",since:"Recorded since",sample:"Browser preview · sample data",suppressed:"Recall was suppressed",allModels:"Show all models",lessModels:"Show fewer models",basis:"Input + output tokens"},
 zh:{session:"本次会话",total:"累计",usage:"Token 用量",input:"输入",output:"输出",requests:"次请求",byModel:"各模型用量",share:"Token · 占比",noModels:"暂无已记录的模型明细",unassigned:"未归属模型",loading:"加载中…",error:"用量刷新失败",retry:"重试",cache:"缓存命中",turn:"本轮 hit",avg:"平均 hit",cached:"缓存",uncached:"未缓存",notReported:"模型未报告",memory:"Memory hits",recall:"最近一次召回 · 匹配记忆",recalls:"已记录召回的命中次数",latestRecall:"当前会话的最近一次召回",noRecall:"尚未召回",context:"会话 context",used:"已使用",compact:"压缩阈值",canonical:"压缩前",projected:"压缩后",reduction:"最近一次 context 压缩",since:"开始记录于",sample:"浏览器预览 · 示例数据",suppressed:"本次召回未注入",allModels:"查看全部模型",lessModels:"收起模型",basis:"输入 + 输出 token"},
 "zh-TW":{session:"本次對話",total:"累計",usage:"Token 用量",input:"輸入",output:"輸出",requests:"次請求",byModel:"各模型用量",share:"Token · 占比",noModels:"暫無已記錄的模型明細",unassigned:"未歸屬模型",loading:"載入中…",error:"用量更新失敗",retry:"重試",cache:"快取命中",turn:"本輪 hit",avg:"平均 hit",cached:"快取",uncached:"未快取",notReported:"模型未回報",memory:"Memory hits",recall:"最近一次召回 · 匹配記憶",recalls:"已記錄召回的命中次數",latestRecall:"目前對話的最近一次召回",noRecall:"尚未召回",context:"對話 context",used:"已使用",compact:"壓縮門檻",canonical:"壓縮前",projected:"壓縮後",reduction:"最近一次 context 壓縮",since:"開始記錄於",sample:"瀏覽器預覽 · 示例資料",suppressed:"本次召回未注入",allModels:"查看全部模型",lessModels:"收起模型",basis:"輸入 + 輸出 token"},
};
export function usageHitRate(hit?:number,miss?:number){ return typeof hit==="number" && typeof miss==="number" && hit+miss>0 ? `${(hit/(hit+miss)*100).toFixed(1)}%` : "—"; }
interface Props {counterId?:string;info:ContextPanelInfo|null; context?:ContextInfo;usage?:WireUsage; refreshKey?:number;error?:boolean;onRetry?:()=>void;}
export function UsageOverview({info,context,usage,refreshKey,error,onRetry,counterId="usage"}:Props){
 const {locale}=useI18n();const c=copy[locale];
 const [scope,setScope]=useState<"session"|"total">("session");const [totals,setTotals]=useState<SavingsTotals|null>(null);const [totalError,setTotalError]=useState(false);const [totalLoading,setTotalLoading]=useState(false);const [showAll,setShowAll]=useState(false);const seq=useRef(0);
 const refreshTotals=useCallback(async()=>{const id=++seq.current;setTotalLoading(true);try{const next=await app.SavingsTotals();if(id===seq.current){setTotals(next);setTotalError(false);}}catch{if(id===seq.current)setTotalError(true);}finally{if(id===seq.current)setTotalLoading(false);}},[]);
 useEffect(()=>{if(scope==="total")void refreshTotals();return()=>{seq.current++;};},[scope,refreshKey,refreshTotals]);
 const total=scope==="total";const failed=total?totalError:error;const loading=total?totalLoading:info===null&&!error;const ready=!failed&&!loading;
 const models=asArray(total?totals?.models:info?.models);const visibleModels=showAll?models:models.slice(0,5);
 const modelTokens=models.reduce((sum,m)=>sum+m.tokens,0);
 const tokens=total?totals?.tokens:models.length?modelTokens:info?.totalTokens;const input=total?totals?.inputTokens:info?.sessionInputTokens;const output=total?totals?.outputTokens:info?.sessionCompletionTokens;const requests=total?totals?.requests:info?.requestCount;
 const hit=total?totals?.cacheHit:info?.sessionCacheHitTokens;const miss=total?totals?.cacheMiss:info?.sessionCacheMissTokens;const reported=(hit??0)+(miss??0)>0;
 const recall=info?.lastRecall;const hits=total?(totals?.recalls?totals.memoryHits:undefined):recall?.query?(recall.suppressed?0:asArray(recall.hits).length):undefined;
 const maintenance=context?.maintenance??info?.maintenance;const receipt=maintenance?.lastReceipt;
 const used=context?.used??info?.usedTokens??0;const window=context?.window??info?.windowTokens??0;const pct=window>0?Math.min(100,Math.max(0,used/window*100)):0;const compact=Math.round((context?.compactRatio??.85)*100);
 return <section className="usage-overview" aria-label={c.usage}>
 {info?.mock&&<p className="usage-preview-label">{c.sample}</p>}
 <div className="usage-period" role="group" aria-label={c.usage} data-scope={scope}><button type="button" aria-pressed={!total} onClick={()=>setScope("session")}><span>{c.session}</span><BorderBeam active={!total}/></button><button type="button" aria-pressed={total} onClick={()=>setScope("total")}><span>{c.total}</span><BorderBeam active={total}/></button></div>
 <div className="usage-total"><h3>{c.usage}</h3><UsageRollingNumber value={ready?tokens:undefined} counterKey={`${counterId}:${scope}`}/><p>{loading?c.loading:failed?c.error:`${requests??0} ${c.requests}`}</p>{failed&&<button className="usage-retry" onClick={()=>total?void refreshTotals():onRetry?.()}><RefreshCw size={13}/>{c.retry}</button>}<div><span>{c.input} <b>{ready&&input!==undefined?formatTokens(input):"—"}</b></span><span>{c.output} <b>{ready&&output!==undefined?formatTokens(output):"—"}</b></span></div></div>
 <section className="usage-models"><header><h3>{c.byModel}</h3><span>{c.share}</span></header>{ready&&visibleModels.length?visibleModels.map((m,i)=><div className="usage-model-row" data-primary={i===0} key={`${m.provider}:${m.model}`}><div className="usage-model-heading"><span title={m.model||c.unassigned}>{m.model.split("/").slice(-1)[0]||c.unassigned}</span><strong>{formatTokens(m.tokens)}</strong></div><MagneticUsageMeter className="usage-model-meter" percent={m.percent}/><footer><span>{m.requests!==undefined?`${m.requests} ${c.requests}`:m.provider}</span><span>{m.percent.toFixed(0)}%</span></footer></div>):<p>{loading?c.loading:failed?c.error:c.noModels}</p>}{models.length>5&&<button onClick={()=>setShowAll(!showAll)}>{showAll?c.lessModels:c.allModels}<ChevronRight size={12}/></button>}{!total&&models.length>0&&<small>{c.basis}</small>}</section>
 <section className="usage-cache"><header><h3>{c.cache}</h3>{!reported&&ready&&<span>{c.notReported}</span>}</header><div className="usage-cache-rates"><div className="usage-cache-average"><span>{c.avg}</span><strong data-reported={ready&&reported}>{ready?usageHitRate(hit,miss):"—"}</strong></div><div className="usage-cache-turn"><span>{c.turn}</span><strong>{usageHitRate(usage?.cacheHitTokens??info?.cacheHitTokens,usage?.cacheMissTokens??info?.cacheMissTokens)}</strong></div></div>{ready&&reported&&<MagneticUsageMeter className="usage-cache-meter" percent={(hit??0)/((hit??0)+(miss??0))*100} height={14} step={6}/>}<dl className="usage-cache-volume"><div><dt>{c.cached}</dt><dd>{ready&&reported?formatTokens(hit??0):"—"}</dd></div><div><dt>{c.uncached}</dt><dd>{ready&&reported?formatTokens(miss??0):"—"}</dd></div></dl></section>
 <details className="usage-memory"><summary><BookOpen size={14}/><div><span>{c.memory}</span><small>{total?c.recalls:c.recall}</small></div><strong>{ready?hits??"—":"—"}</strong><ChevronRight size={13}/></summary>{total&&<p>{c.latestRecall}</p>}{recall?.suppressed&&<p>{c.suppressed}: {recall.suppressed}</p>}{!recall?.query&&<p>{c.noRecall}</p>}{asArray(recall?.hits).map(h=><article key={`${h.id}:${h.revision}`}><header><strong>{h.title||h.name}</strong><span>{h.scope}</span></header><p>{h.snippet}</p><small>{h.reason}</small></article>)}</details>
 {total&&totals?.since&&<p className="usage-since">{c.since} {totals.since}</p>}
 <details className="usage-context"><summary><span>{c.context}</span><span>{formatTokens(used)} / {window>0?formatTokens(window):"—"}</span><ChevronRight size={13}/></summary><div>{maintenance&&<><p><span>{c.canonical}</span><strong>{formatTokens(maintenance.canonicalTokens??0)}</strong></p><p><span>{c.projected}</span><strong>{formatTokens(maintenance.projectedTokens??0)}</strong></p></>}{receipt?.status==="applied"&&<p><span>{c.reduction}</span><strong>{formatTokens(receipt.savedTokens??0)}</strong></p>}</div></details><MagneticUsageMeter className="usage-context-meter" percent={pct} height={4}/><div className="usage-context-foot"><span><strong>{window>0?`${pct.toFixed(1)}%`:"—"}</strong> {c.used}</span><span>{c.compact} {compact}%</span></div>
 </section>;
}
