import assert from "node:assert/strict";
import React, { act } from "react";
import { JSDOM } from "jsdom";
import { createRoot } from "react-dom/client";
import { BorderBeam } from "../components/magicui/BorderBeam";

const dom = new JSDOM('<div id="root"></div>', { pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true });
let hidden = false;
let reduced = false;
Object.defineProperty(document, "visibilityState", { get: () => hidden ? "hidden" : "visible" });
const listeners = new Set<() => void>();
Object.defineProperty(window, "matchMedia", { value: () => ({ get matches() { return reduced; }, addEventListener: (_: string, fn: () => void) => listeners.add(fn), removeEventListener: (_: string, fn: () => void) => listeners.delete(fn) }) });
const animations: Array<{ cancelled: boolean; plays: number; pauses: number; frames: Keyframe[]; options: KeyframeAnimationOptions }> = [];
Object.defineProperty(dom.window.HTMLElement.prototype, "animate", { value: function(frames: Keyframe[], options: KeyframeAnimationOptions) {
  const animation = { cancelled: false, plays: 0, pauses: 0, frames, options };
  animations.push(animation);
  return { play() { animation.plays++; }, pause() { animation.pauses++; }, cancel() { animation.cancelled = true; } };
} });
const root = createRoot(document.getElementById("root")!);
await act(async () => root.render(<BorderBeam />));
assert.equal(animations.length, 1, "a visible beam owns one browser animation");
assert.equal(animations[0].options.iterations, Infinity);
assert.equal(animations[0].frames[1].offsetDistance, "100%", "the light travels around the edge");
assert.equal(document.querySelector('.semantix-border-beam')?.getAttribute("aria-hidden"), "true", "decoration is not a second interactive target");
hidden = true;
document.dispatchEvent(new dom.window.Event("visibilitychange"));
assert.equal(animations[0].pauses, 1, "hidden tabs pause the existing animation");
hidden = false;
document.dispatchEvent(new dom.window.Event("visibilitychange"));
assert.equal(animations.length, 1, "visibility changes do not create extra loops");
assert.equal(animations[0].plays, 2, "the existing animation resumes");
reduced = true;
listeners.forEach(fn => fn());
assert.equal(animations[0].cancelled, true, "reduced motion cancels immediately");
reduced = false;
listeners.forEach(fn => fn());
assert.equal(animations.length, 2, "motion can be restored without a reload");
await act(async () => root.render(<BorderBeam active={false} />));
assert.equal(animations[1].cancelled, true, "changing the selected button releases its animation");
assert.equal(document.querySelector('.semantix-border-beam'), null);
assert.equal(listeners.size, 0, "unmount removes preference listeners");
await act(async () => root.unmount());
dom.window.close();
console.log("Border beam: 12 checks passed");
