import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import React, { act, Profiler } from "react";
import { createRoot } from "react-dom/client";
import { HyperTextLine } from "../components/HyperTextLine";

const dom = new JSDOM('<div id="root"></div>', { pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true });
Object.defineProperty(globalThis, "navigator", { configurable: true, value: dom.window.navigator });
let now = 0;
Object.defineProperty(window.performance, "now", { value: () => now });
let id = 0;
const timers = new Map<number, { due: number; run: () => void }>();
const frames = new Map<number, FrameRequestCallback>();
window.setTimeout = ((run: () => void, delay: number) => { const key = ++id; timers.set(key, { due: now + delay, run }); return key; }) as typeof window.setTimeout;
window.clearTimeout = key => { timers.delete(key); };
window.requestAnimationFrame = run => { const key = ++id; frames.set(key, run); return key; };
window.cancelAnimationFrame = key => { frames.delete(key); };
let changed = () => {};
const preference = { matches: false, addEventListener: (_: string, fn: () => void) => { changed = fn; }, removeEventListener: () => {} };
window.matchMedia = (() => preference) as unknown as typeof window.matchMedia;
let visible = true;
Object.defineProperty(document, "visibilityState", { get: () => visible ? "visible" : "hidden" });
const tick = async (elapsed: number) => {
  await act(async () => {
    now += elapsed;
    for (const [key, timer] of [...timers]) if (timer.due <= now) { timers.delete(key); timer.run(); }
  });
};
const paint = async (elapsed: number) => {
  await act(async () => { now += elapsed; const pending = [...frames.values()]; frames.clear(); pending.forEach(run => run(now)); });
};
const root = createRoot(document.getElementById("root")!);
let commits = 0;
const messages = ["Build a feature.", "Find the bug.", "Review your changes."];
await act(async () => { root.render(<Profiler id="caption" onRender={() => commits++}><HyperTextLine messages={messages}/></Profiler>); });
const visual = () => document.querySelector(".semantix-hypertext__visual")!.textContent;
const accessible = () => document.querySelector(".sr-only")!.textContent;
const hover = async (pointerType = "mouse") => {
  await act(async () => {
    const event = new dom.window.MouseEvent("pointerover", { bubbles: true });
    Object.defineProperty(event, "pointerType", { value: pointerType });
    document.querySelector(".semantix-hypertext")!.dispatchEvent(event);
  });
};
assert.equal(visual(), messages[0], "mount shows readable text without a startup scramble");
assert.equal(frames.size, 0);
assert.equal(document.querySelectorAll(".semantix-hypertext__reserve").length, 3, "all messages reserve one common footprint");
await tick(2999);
assert.equal(frames.size, 0, "idle animation never starts before three seconds");
window.dispatchEvent(new dom.window.MouseEvent("pointermove"));
await tick(1);
await tick(2998);
assert.equal(frames.size, 0, "pointer activity restarts the idle deadline");
await tick(1);
assert.equal(frames.size, 1, "three idle seconds trigger exactly one animation");
const steadyCommits = commits;
await paint(16);
assert.notEqual(visual(), messages[1], "letters scramble before revealing the next message");
assert.equal(accessible(), messages[0], "assistive text never receives random glyphs");
assert.equal(commits, steadyCommits, "animation frames avoid React renders");
await paint(640);
assert.equal(visual(), messages[1]);
assert.equal(accessible(), messages[1]);
assert.equal(frames.size, 0, "the animation stops after revealing the final text");
await hover();
await hover();
assert.equal(frames.size, 1, "repeated hover while animating does not queue more transitions");
await paint(640);
assert.equal(visual(), messages[2], "hover advances one message");
await hover("touch");
assert.equal(frames.size, 0, "touch entry does not produce a hover animation");
visible = false;
document.dispatchEvent(new dom.window.Event("visibilitychange"));
assert.equal(timers.size, 0, "hidden windows stop the idle timer");
await tick(5000);
assert.equal(visual(), messages[2]);
visible = true;
document.dispatchEvent(new dom.window.Event("visibilitychange"));
assert.equal(timers.size, 1, "returning to the window starts a fresh idle deadline");
preference.matches = true;
changed();
await hover();
assert.equal(visual(), messages[0], "reduced motion still allows message changes");
assert.equal(frames.size, 0, "reduced motion skips the letter flicker");
const overlay = document.createElement("div");
overlay.className = "settings-modal-backdrop";
document.body.append(overlay);
await tick(3000);
assert.equal(visual(), messages[0], "covered welcome text does not rotate behind Settings");
overlay.remove();
window.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "a" }));
await tick(2999);
assert.equal(visual(), messages[0], "typing restarts the idle deadline");
await tick(1);
assert.equal(visual(), messages[1], "idle reduced-motion mode changes text without scrambling");
preference.matches = false;
await act(async () => { root.render(<HyperTextLine messages={["写一个功能。", "一起修复问题。"]}/>); });
assert.equal(visual(), "写一个功能。", "locale changes reset the message to readable localized text");
await hover();
await paint(16);
assert.match(visual()!, /^[\p{Script=Han}。]+$/u, "Chinese messages use Chinese scramble glyphs");
await paint(640);
assert.equal(visual(), "一起修复问题。");
await hover();
await act(async () => { root.unmount(); });
assert.equal(frames.size, 0, "unmount cancels an active animation");
assert.equal(timers.size, 0, "unmount cancels the idle timer");
console.log("Hyper text: hover, idle, activity reset, accessibility, reduced motion, locale and cleanup checks passed.");
