import assert from "node:assert/strict";
import React, { act } from "react";
import { JSDOM } from "jsdom";
import { createRoot } from "react-dom/client";
import { UsageRollingNumber, upwardDigitSteps, formatRollingTokens } from "../components/UsageRollingNumber";

const dom = new JSDOM('<div id="root"></div>', { pretendToBeVisual:true });
Object.assign(globalThis, {window:dom.window, document:dom.window.document, IS_REACT_ACT_ENVIRONMENT:true});
let reduced = false;
const listeners = new Set<() => void>();
Object.defineProperty(window,"matchMedia",{value:()=>({get matches(){return reduced;},addEventListener:(_event:string,fn:()=>void)=>listeners.add(fn),removeEventListener:(_event:string,fn:()=>void)=>listeners.delete(fn)})});
const animations: Array<{frames:Keyframe[]; options:KeyframeAnimationOptions; cancelled:boolean; onfinish:(()=>void)|null; cancel:()=>void}> = [];
Object.defineProperty(dom.window.HTMLElement.prototype,"animate",{value:function(frames:Keyframe[],options:KeyframeAnimationOptions){const animation={frames,options,cancelled:false,onfinish:null as (()=>void)|null,cancel(){this.cancelled=true;}};animations.push(animation);return animation;}});
const root=createRoot(document.getElementById("root")!);
const render=async(value:number|undefined,key="session-a")=>act(async()=>root.render(<UsageRollingNumber value={value} counterKey={key}/>));
assert.deepEqual(upwardDigitSteps("9","1"),["9","0","1"]);
assert.deepEqual(upwardDigitSteps("3","3"),["3"]);
assert.equal(formatRollingTokens(0),"0");
assert.equal(formatRollingTokens(1_000_000),"1.0M");
await render(34900);
assert.equal(animations.length,0,"initial load stays settled");
await render(35000);
assert.equal(animations.length,2,"only changed decimal/count digits roll");
assert.ok(animations.every(a=>String(a.frames[1].transform).startsWith("translateY(-")),"all reels move upward");
assert.equal(document.querySelector("strong")?.getAttribute("aria-label"),"35.0k","accessible value is current, never intermediate digits");
const firstBatch=[...animations];
await render(35100);
assert.ok(firstBatch.every(a=>a.cancelled),"new usage cancels obsolete reels");
animations.filter(a=>!a.cancelled).forEach(a=>a.onfinish?.());
assert.equal(document.querySelectorAll('[data-rolling=true]').length,0,"reels release their animated state after settling");
const count=animations.length;
await render(30000);
assert.equal(animations.length,count,"decreases do not mimic token spending");
await render(50000,"session-b");
assert.equal(animations.length,count,"switching sessions does not spin");
await render(undefined,"session-b");
assert.equal(document.querySelector("strong")?.getAttribute("aria-label"),"—");
await render(10000,"session-b");
assert.equal(animations.length,count,"first reported usage after unknown is static");
reduced=true;
await render(10100,"session-b");
assert.equal(animations.length,count,"reduced motion skips reels");
reduced=false;
await render(10200,"session-b");
assert.ok(animations.length>count);
reduced=true;listeners.forEach(fn=>fn());
assert.equal(document.querySelectorAll('[data-rolling=true]').length,0,"changing reduced motion immediately settles active reels");
await act(async()=>root.unmount());
assert.equal(listeners.size,0,"unmount removes motion listeners");
dom.window.close();
console.log("Usage rolling number: 16 checks passed");
