import assert from "node:assert/strict";
import { initialState, reducer } from "../lib/useController";
import { useLayoutStore } from "../store/layout";
import { WorkspaceDisclosure } from "../lib/workspaceDisclosure";

const layout = () => useLayoutStore.getState();
assert.equal(layout().workspacePanelOpen, false, "launch starts without the right dock");
layout().syncWorkspaceDisclosure("chat-a", 0);
let state = reducer(initialState, { type: "user", text: "Preview question", seq: 1, submissionId: "a" });
layout().syncWorkspaceDisclosure("chat-a", state.workStartSeq);
assert.equal(layout().workspacePanelOpen, false, "an optimistic submit is not accepted work");
state = reducer(state, { type: "event", e: { kind: "turn_started", tabId: "chat-a", submissionId: "a" } });
layout().syncWorkspaceDisclosure("chat-a", state.workStartSeq);
assert.equal(layout().workspacePanelOpen, true, "accepted work reveals the dock");
assert.equal(layout().rightDockMode, "context", "automatic disclosure opens Usage");
state = reducer(state, { type: "event", e: { kind: "turn_done" } });
layout().syncWorkspaceDisclosure("chat-a", state.workStartSeq);
assert.equal(layout().workspacePanelOpen, true, "finishing a turn leaves its numbers visible");
layout().setWorkspacePanelOpen(false);
layout().syncWorkspaceDisclosure("chat-a", state.workStartSeq + 1);
assert.equal(layout().workspacePanelOpen, false, "later work does not reopen a manually closed dock");
layout().setRightDockMode("files");
layout().setWorkspacePanelOpen(true);
layout().syncWorkspaceDisclosure("chat-a", state.workStartSeq + 2);
assert.equal(layout().rightDockMode, "files", "work does not interrupt the chosen Files view");
layout().syncWorkspaceDisclosure("chat-b", 0);
assert.equal(layout().workspacePanelOpen, false, "another empty chat starts hidden");
layout().syncWorkspaceDisclosure("chat-b", 1);
assert.equal(layout().workspacePanelOpen, true, "the new chat gets its own first-work reveal");
layout().syncWorkspaceDisclosure("chat-a", state.workStartSeq + 2);
assert.equal(layout().rightDockMode, "files", "returning to a chat restores its chosen view");
assert.equal(layout().workspacePanelOpen, true, "returning preserves the user's open choice");
layout().resetWorkspaceDisclosure("chat-a", 0);
assert.equal(layout().workspacePanelOpen, false, "New chat hides the dock even when the surface is reused");
layout().syncWorkspaceDisclosure("chat-a", 1);
assert.equal(layout().workspacePanelOpen, true, "a reused fresh surface reveals on its first work");
const launch = new WorkspaceDisclosure();
assert.equal(launch.visit("restored-history", 6).open, false, "restored historical work does not reveal at startup");
assert.equal(launch.visit("restored-history", 7).open, true, "new work after startup does reveal");
const failed = reducer(initialState, { type: "send_failed", submissionId: "failed", error: "test" });
assert.equal(failed.workStartSeq, 0, "failed submissions cannot count as accepted work");
console.log("Workspace disclosure: 15 checks passed");
