package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// initTemplate is the semantix.toml generated by `semantix init` (U21 §3.2):
// a commented template mirroring semantix.example.toml so every field is
// discoverable and editable.
const initTemplate = `# semantix.toml — generated by ` + "`semantix init`" + `
# 生效优先级：CLI flag > env（SEMANTIX_*）> 本文件 > 内置默认。

[project]
name = "my-project"          # 项目 slug（切片 scope=project 的聚合键）

[store]
# 切片库路径（extract/lookup/inject/verify 的 --db 默认值）
db = ".semantix/project.db"
scope = "project"           # 默认切片作用域：session | project | user
max_slices = 5000           # 库条目上限（超限按价值评分归档到 <db>.archive.jsonl；0 = 不限）

[score]                     # 价值评分（gc / gateway 启动时批算，决定淘汰序）
half_life_days = 30         # 时效半衰期：30 天不用价值减半
grace_days = 7              # 新切片保护窗：淘汰序中排最后（不豁免上限）

[retrieval]
retriever = "hybrid"        # bm25 | vector | hybrid（RRF 融合）
limit = 5                   # search 默认 top-k
vector_dim = 256            # HashEmbedder 维度（模型级 Embedder 接入后忽略）

[inject]
budget = 4096               # L2 注入块最大字节数（整切片截断）
top_k = 5                   # 注入候选切片数

[verify]
holdout = 0.3               # 离线回放验证：后 30% 会话作为测试流
target_hit_rate = 0.7       # M0-2 验收目标命中率

[cost]                      # 成本对比参数
tool_tokens = 300           # 每工具调用输出 token 估算
reuse_ratio = 0.8           # 注入替代重复步骤比例
input_price_usd = 0.27      # 每 1M 输入 token（cache miss）
cache_price_usd = 0.07      # 每 1M 输入 token（cache hit）
output_price_usd = 1.10     # 每 1M 输出 token
`

type initData struct {
	Created []string `json:"created"`
	Skipped []string `json:"skipped"`
}

// runInit generates semantix.toml + the .semantix/ directory skeleton (U21 §3.2).
func runInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	configPath := fs.String("config", "semantix.toml", "output config file path")
	force := fs.Bool("force", false, "overwrite an existing semantix.toml")
	jsonOut := fs.Bool("json", false, "output as JSON")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 2
	}
	if fs.NArg() > 0 {
		fmt.Fprintf(stderr, "init: unexpected argument %q\n", fs.Arg(0))
		return 2
	}

	var created, skipped []string

	// semantix.toml: refuse to overwrite unless --force.
	if _, err := os.Stat(*configPath); err == nil && !*force {
		fmt.Fprintf(stderr, "init: %s already exists; re-run with --force to overwrite\n", *configPath)
		return 1
	}
	if err := os.WriteFile(*configPath, []byte(initTemplate), 0o644); err != nil {
		fmt.Fprintf(stderr, "init: write %s: %v\n", *configPath, err)
		return 1
	}
	created = append(created, *configPath)

	// .semantix/ skeleton (next to semantix.toml), idempotent.
	dir := filepath.Join(filepath.Dir(*configPath), ".semantix")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		fmt.Fprintf(stderr, "init: mkdir %s: %v\n", dir, err)
		return 1
	}
	gitkeep := filepath.Join(dir, ".gitkeep")
	if _, err := os.Stat(gitkeep); os.IsNotExist(err) {
		if err := os.WriteFile(gitkeep, nil, 0o644); err != nil {
			fmt.Fprintf(stderr, "init: write %s: %v\n", gitkeep, err)
			return 1
		}
		created = append(created, gitkeep)
	} else {
		skipped = append(skipped, gitkeep)
	}

	if *jsonOut {
		if err := writeJSON(stdout, okEnvelope("init", initData{Created: created, Skipped: skipped})); err != nil {
			fmt.Fprintf(stderr, "init: %v\n", err)
			return 1
		}
		return 0
	}
	for _, c := range created {
		fmt.Fprintf(stdout, "created %s\n", c)
	}
	for _, s := range skipped {
		fmt.Fprintf(stdout, "skipped %s (already exists)\n", s)
	}
	return 0
}
